builder check on linux os

diff --git a/bin/builder b/bin/builder
--- a/bin/builder
+++ b/bin/builder
@@ -58,9 +58,6 @@ exit 1
 # MAIN BODY #
 # ######### #
 
-## pkg_sem
-pkg_sem=0
-
 ## recording
 perl_sem=0
 lidn_sem=0
@@ -125,7 +122,7 @@ kernel_config_done=0
 PWD=`dirname $0`
 . ${PWD}/setenv
 
-while getopts ":a:b:m:p:ht" ar
+while getopts ":a:b:m:p:ht" arg
 do
     case "${arg}" in
 
@@ -167,7 +164,6 @@ do
     m)
         module=$OPTARG
         case "$module" in
-
             
             perl)
                 perl_sem=1
@@ -214,12 +210,10 @@ do
             ;;
 
             rpm)
-                pkg_sem=1
                 rpm_sem=1
             ;;
 
             deb)
-                pkg_sem=1
                 deb_sem=1
             ;;
 
@@ -503,9 +497,19 @@ case "$module" in
     echo "" > ${BUILD_PATH}/${BUILD_LOG}
 
     if [ $rpm_sem -eq 1 ]; then
-        build_rec_pkg
+        if [ "x$DIST_ID" = "xrhel" -o "x$DIST_ID" = "xcentos" ]; then
+            build_rec_pkg
+        else
+            echo "Error: not a RPM installation, cannot build rpm pkg"
+            exit 3
+        fi
     elif [ $deb_sem -eq 1 ]; then
-        build_rec_pkg
+        if [ "x$DIST_ID" = "xdebian" -o "x$DIST_ID" = "xubuntu" ]; then
+            build_rec_pkg
+        else
+            echo "Error: not a RPM installation, cannot build deb pkg"
+            exit 3
+        fi
     else 
         build_rec_perl
         build_rec_ossl
